### ISSUE TITLE
Even if there are more than 10,000 objects in the ListView, the number of objects will not be displayed in the results more than 10,000.

### ISSUE THREAD

**Issue by johnvonneumann7** [rhblind/drf-haystack#167]
I have about 300,000 index objects, and even if I don't filter and just get them all in the View, the limit is still 10,000.
Is there an option to work around this?

![image](https://user-images.githubusercontent.com/78252058/137437785-ac91cb1a-1b86-4791-98b1-ccdb0f7c9779.png)
![image](https://user-images.githubusercontent.com/78252058/137437862-8f6a197d-4efe-40b7-956c-6a7f29e557ad.png)

**Comment by rhblind** [comment]
Hey, sorry for late response here.
I really don't know what the cause is, but if I should guess I'd look into [Elasticsearch index settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings). Check out the `index.max_result_window` setting maybe?

**Comment by mka142** [comment]
It's rather question related to django-haystack itself. There is already existing issue: https://github.com/django-haystack/django-haystack/issues/1532
